### PR TITLE
feat: convert lavalink interface types to zod objects

### PR DESCRIPTION
**Pull request by 0t4u**
Allows for better validation of responses and enforces limits for numerical options on some options.

This introduces zod as a dependency.

Also improves some code documentation comments (supersedes #183).

### CODE REVIEW

**Review by Deivu — COMMENTED** [review]
Is this backwards compatible with the current v4 code base? if so we can release this in v4

**Comment by 0t4u** [comment]
This should in theory be backwards compatible but the types do change by quite a bit, and enums are completely changed.

**Comment by 0t4u** [comment]
I would not recommend merging to v4

**Comment by Deivu** [comment]
Then we will ship this with v5

**Pull request merged**
