### PR TITLE
Fix: emit shoukaku type.

### PR DESCRIPTION
**Pull request by EvilG-MC**
This should solve the type en problem: #179 

I manually added the type for some reason, it takes the type of the EventEmitter, but in my case the method does not appear, so it was added manually, in `Shoukaku.ts` and also in `Player.ts`.

### CODE REVIEW

**Comment by KagChi** [comment]
Do not ignore pnpm lockfiles

**Comment by EvilG-MC** [comment]
> Do not ignore pnpm lockfiles

I just followed the fact that the package-lock.json is in the gitignore

**Comment by KagChi** [comment]
package-lock.json are not required if we use pnpm

**Comment by EvilG-MC** [comment]
> package-lock.json are not required if we use pnpm

My point is that I don't even want to have to force you to use a specific package manager, just the one you want.

**Comment by Deivu** [comment]
https://github.com/shipgirlproject/Shoukaku/issues/179#issuecomment-2198244783

Is the pr tested, seems like the issue persist till now

**Comment by EvilG-MC** [comment]
> [#179 (comment)](https://github.com/shipgirlproject/Shoukaku/issues/179#issuecomment-2198244783)
> 
> Is the pr tested, seems like the issue persist till now

It's quite strange, I tried it locally, because as I mentioned, in my case `emit` did not appear both in the npmjs version and in the commit where the reverse was made

**Comment by EvilG-MC** [comment]
I'm going to try again, because it's quite strange

**Pull request merged**
